---
title: "STAT 240 - Assignment 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

```{r, echo=TRUE}
radius = c(1, 3, 5, 7)
volume = 4/3*pi*radius^3
par(mfrow=c(4, 1), mar=c(4, 4, 2, 1))

plot(radius, volume, main="Line-plot of radius vs. volume of a sphere (type='l')",
     xlab="radius", ylab="volume", 
     ylim=c(0, 1500), xlim=c(-1, 9), 
     type='l', col="red", lwd=3)

plot(radius, volume, main="Point-plot of radius vs. volume of a sphere (type='p')",
     xlab="radius", ylab="volume", 
     ylim=c(0, 1500), xlim=c(-1, 9), 
     type='p', col="purple", lwd=4)

plot(radius, volume, main="Line + Point plot of radius vs. volume of a sphere (type='b')",
     xlab="radius", ylab="volume", 
     ylim=c(0, 1500), xlim=c(-1, 9), 
     type='b', col="blue", lwd=2)

plot(radius, volume, main="Empty plot of radius vs. volume of a sphere (type='n')",
     xlab="radius", ylab="volume", 
     ylim=c(0, 1500), xlim=c(-1, 9), 
     type='n', col="black", lwd=3.5)
```

